require 'launchy'
require 'net/ftp'
require_relative 'API'

class HTMLwritter < API
@fpath = File.join(File.dirname(__FILE__), 'HTML/feeds.html')
  def self.ftp_upload
    puts "Conectando a servidor FTP".yellow
    f = File.open(@fpath)
    ftpath='simonbermudez.com.ve/htdocs/HACK/IMDB/index.html'
    Net::FTP.open('ftp.byethost16.com', self.decode("OIQ_I1QzI641"), self.decode("imZZfKveIz4G")){ |ftp| ftp.putbinaryfile(f, ftpath) }
    puts "Carga satisfactoria".cyan
    puts "Actualizando servidor...".yellow
    sleep 5
    ftpath
  end

  def self.write_movie_chart(movie = {}) #Hash de la info de la pelicula
    puts "Escribiendo HTML de feeds...".yellow
    title = "IMDB SEARCH"
    movie_title = movie["Title"]
        File.open(@fpath, 'w') do |file|
          file.puts "<!DOCTYPE html>"
          file.puts "<html lang=\"en\">"
          file.puts "<head>"
          file.puts "	<meta charset=\"UTF-8\">"
          file.puts "	<meta content=\"IE=edge\" http-equiv=\"X-UA-Compatible\">"
          file.puts "	<meta content=\"initial-scale=1.0, maximum-scale=1.0, user-scalable=no, width=device-width\" name=\"viewport\">"
          file.puts "	<title>#{title}</title>"
          file.puts "	<link href=\"./css/base.min.css\" rel=\"stylesheet\">"
          file.puts "	<link href=\"./css/project.min.css\" rel=\"stylesheet\">"
          file.puts "</head>"
          file.puts "<body class=\"page-brand\">"
          file.puts "	<header class=\"header header-transparent header-waterfall ui-header\">"
          file.puts "		<ul class=\"nav nav-list pull-left\">"
          file.puts "			<li>"
          file.puts "				<a data-toggle=\"menu\" href=\"#ui_menu\">"
          file.puts "					<span class=\"icon icon-lg\">menu</span>"
          file.puts "				</a>"
          file.puts "			</li>"
          file.puts "		</ul>"
          file.puts "		<a class=\"header-logo header-affix-hide margin-left-no margin-right-no\" data-offset-top=\"213\" data-spy=\"affix\" href=\"index.html\">#{title}</a>"
          file.puts "		<span class=\"header-logo header-affix margin-left-no margin-right-no\" data-offset-top=\"213\" data-spy=\"affix\">Data Tables</span>"
          file.puts "	</header>"
          file.puts "	<nav aria-hidden=\"true\" class=\"menu\" id=\"ui_menu\" tabindex=\"-1\">"
          file.puts "		<div class=\"menu-scroll\">"
          file.puts "			<div class=\"menu-content\">"
          file.puts "				<a class=\"menu-logo\" href=\"index.html\">#{title} - Simon Bermudez</a>"
          file.puts "				<ul class=\"nav\">"
          file.puts "					<li>"
          file.puts "						<a class=\"waves-attach\" data-toggle=\"collapse\" href=\"#ui_menu_components\">Components</a>"
          file.puts "						<ul class=\"menu-collapse collapse in\" id=\"ui_menu_components\">"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-button.html\">Buttons</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-button-fab.html\">Buttons<small class=\"margin-left-xs\">(Floating Action Button)</small></a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-card.html\">Cards</a>"
          file.puts "							</li>"
          file.puts "							<li class=\"active\">"
          file.puts "								<a class=\"waves-attach\" href=\"ui-data-table.html\">Data Tables</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-dialog.html\">Dialogs</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-dropdown-menu.html\">Menus</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-nav-drawer.html\">Navigation Drawers</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-picker.html\">Pickers</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-progress.html\">Progress</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-selection-control.html\">Selection Controls</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-snackbar.html\">Snackbars</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-stepper.html\">Steppers</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-tab.html\">Tabs</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-text-field.html\">Text Fields</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-toolbar.html\">Toolbars</a>"
          file.puts "							</li>"
          file.puts "						</ul>"
          file.puts "					</li>"
          file.puts "					<li>"
          file.puts "						<a class=\"collapsed waves-attach\" data-toggle=\"collapse\" href=\"#ui_menu_extras\">Extras</a>"
          file.puts "						<ul class=\"menu-collapse collapse\" id=\"ui_menu_extras\">"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-avatar.html\">Avatars</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-icon.html\">Icons</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-label.html\">Labels</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-nav.html\">Navs</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-tile.html\">Tiles</a>"
          file.puts "							</li>"
          file.puts "						</ul>"
          file.puts "					</li>"
          file.puts "					<li>"
          file.puts "						<a class=\"collapsed waves-attach\" data-toggle=\"collapse\" href=\"#ui_menu_javascript\">Javascript</a>"
          file.puts "						<ul class=\"menu-collapse collapse\" id=\"ui_menu_javascript\">"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-affix.html\">Affix</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-collapse.html\">Collapse</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-dropdown-menu.html\">Dropdown</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-modal.html\">Modals</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"ui-tab.html\">Togglable Tabs</a>"
          file.puts "							</li>"
          file.puts "						</ul>"
          file.puts "					</li>"
          file.puts "					<li>"
          file.puts "						<a class=\"collapsed waves-attach\" data-toggle=\"collapse\" href=\"#ui_menu_samples\">Sample Pages</a>"
          file.puts "						<ul class=\"menu-collapse collapse\" id=\"ui_menu_samples\">"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"page-login.html\">Login Page</a>"
          file.puts "							</li>"
          file.puts "							<li>"
          file.puts "								<a class=\"waves-attach\" href=\"page-picker.html\">Picker Page</a>"
          file.puts "							</li>"
          file.puts "						</ul>"
          file.puts "					</li>"
          file.puts "				</ul>"
          file.puts "			</div>"
          file.puts "		</div>"
          file.puts "	</nav>"
          file.puts "	<main class=\"content\">"
          file.puts "		<div class=\"content-header ui-content-header\">"
          file.puts "			<div class=\"container\">"
          file.puts "				<div class=\"row\">"
          file.puts "					<div class=\"col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2\">"
          file.puts "						<h1 class=\"content-heading\">#{movie["Title"]}</h1>"
          file.puts "					</div>"
          file.puts "				</div>"
          file.puts "			</div>"
          file.puts "		</div>"
          file.puts "		<div class=\"container\">"
          file.puts "			<div class=\"row\">"
          file.puts "				<div class=\"col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2\">"
          file.puts "					<section class=\"content-inner margin-top-no\">"
          file.puts "						<div class=\"card\">"
          file.puts "							<div class=\"card-main\">"
          file.puts "							</div>"
          file.puts "						</div>"
          file.puts "						<h2 class=\"content-sub-heading\">Movie Info</h2>"



          file.puts "						<div class=\"card\">"
          file.puts "							<div class=\"card-main\">"
          file.puts "								<div class=\"card-inner margin-bottom-no\">"
          file.puts "									<p class=\"card-heading\">#{movie["Title"]}</p>"
          file.puts "									<div class=\"card-table\">"
          file.puts "										<div class=\"table-responsive\">"
          file.puts "											<table class=\"table\" title=\"A table within a card\">"
          file.puts "												<thead>"
          file.puts "													<tr>"
          file.puts "														<th>Data</th>"
          file.puts "														<th>Content</th>"
          file.puts "													</tr>"
          file.puts "												</thead>"
          file.puts "												<tbody>"
          file.puts "													<tr>"
          file.puts "														<td>Year</td>"
          file.puts "														<td>#{movie["Year"]}</td>"
          file.puts "													</tr>"
          file.puts "													<tr>"
          file.puts "														<td>Rated</td>"
          file.puts "														<td>#{movie["Rated"]}</td>"
          file.puts "													</tr>"
          file.puts "													<tr>"
          file.puts "														<td>Released</td>"
          file.puts "														<td>#{movie["Released"]}</td>"
          file.puts "													</tr>"
          file.puts "													<tr>"
          file.puts "														<td>Runtime</td>"
          file.puts "														<td>#{movie["Runtime"]}</td>"
          file.puts "													</tr>"
          file.puts "													<tr>"
          file.puts "														<td>Genre</td>"
          file.puts "														<td>#{movie["Genre"]}</td>"
          file.puts "													</tr>"
          file.puts "													<tr>"
          file.puts "														<td>Director</td>"
          file.puts "														<td>#{movie["Director"]}</td>"
          file.puts "													</tr>"
          file.puts "													<tr>"
          file.puts "														<td>Writer</td>"
          file.puts "														<td>#{movie["Writer"]}</td>"
          file.puts "													</tr>"
          file.puts "													<tr>"
          file.puts "														<td>Actors</td>"
          file.puts "														<td>#{movie["Actors"]}</td>"
          file.puts "													</tr>"
          file.puts "													<tr>"
          file.puts "														<td>Language</td>"
          file.puts "														<td>#{movie["Language"]}</td>"
          file.puts "													</tr>"
          file.puts "                                                    													                           <tr>"
          file.puts "														<td>Country</td>"
          file.puts "														<td>#{movie["Country"]}</td>"
          file.puts "													</tr>"
          file.puts "                                                    													                           <tr>"
          file.puts "														<td>Awards</td>"
          file.puts "														<td>#{movie["Awards"]}</td>"
          file.puts "													</tr>"
          file.puts "						                           <tr>"
          file.puts "														<td>Poster</td>"
          file.puts "														<td>#{movie["Poster"]}</td>"
          file.puts "													</tr>                         						                           <tr>"
          file.puts "														<td>Metascore</td>"
          file.puts "														<td>#{movie["Metascore"]}</td>"
          file.puts "													</tr>    "
          file.puts "                                                    "
          file.puts "                                                    <tr>"
          file.puts "                                                        <td>imdbRating</td>"
          file.puts "														<td>#{movie["imdbRating"]}</td>"
          file.puts "													</tr>  "
          file.puts "                                                    <tr>"
          file.puts "														<td>imdbVotes</td>"
          file.puts "														<td>#{movie["imdbVotes"]}</td>"
          file.puts "													</tr>                                                                             <tr>"
          file.puts "														<td>imdbID</td>"
          file.puts "														<td>#{movie["imdbID"]}</td>"
          file.puts "													</tr> "
          file.puts "                                                    <tr>"
          file.puts "														<td>Type</td>"
          file.puts "														<td>#{movie["Type"]}</td>"
          file.puts "													</tr>                                                     "
          file.puts "												</tbody>"
          file.puts "											</table>"
          file.puts "										</div>"
          file.puts "									</div>"
          file.puts "								</div>"

          file.puts "								<div class=\"card-action\">"
          file.puts "									<div class=\"card-action-btn pull-right\">"
          file.puts "										<a class=\"btn btn-flat waves-attach\" href=\"javascript:void(0)\"><span class=\"icon\">chevron_left</span></a>"
          file.puts "										<a class=\"btn btn-flat waves-attach\" href=\"javascript:void(0)\"><span class=\"icon\">chevron_right</span></a>"
          file.puts "									</div>"
          file.puts "								</div>"
          file.puts "							</div>"
          file.puts "						</div>"
          file.puts "					</section>"
          file.puts "				</div>"
          file.puts "			</div>"
          file.puts "		</div>"
          file.puts "	</main>"
          file.puts "	<footer class=\"ui-footer\">"
          file.puts "		<div class=\"container\">"
          file.puts "			<p>#{title}</p>"
          file.puts "		</div>"
          file.puts "	</footer>"
          file.puts ""
          file.puts "	<!-- js -->"
          file.puts "	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js\"></script>"
          file.puts "	<script src=\"./js/base.min.js\"></script>"
          file.puts "	<script src=\"./js/project.min.js\"></script>"
          file.puts "</body>"
          file.puts "</html>"
        end
        Launchy.open(@fpath)
      #Launchy.open(ftp_upload)
      puts "Abriendo en el navegador...".yellow
      end

      def self.decode(text) #hice esta funcion para no poner mi usuario y mi contrase;a FTP a simple vista
        puts "Decodificando #{text}".yellow
        a = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        e = "MOhqm0PnycUZeLdK8YvDCgNfb7FJtiHT52BrxoAkas9RWlXpEujSGI64VzQ31w"
        return text.tr(e, a)
      end

      def self.write_card_search(movie_hash) #Hash de la info de la pelicula
        puts "Escribiendo HTML de feeds...".yellow
        title = "IMDB SEARCH"
        movies = movie_hash["Search"]
            File.open(@fpath, 'w') do |file|
                file.puts "<!DOCTYPE html>"
                file.puts "<html lang=\"en\">"
                file.puts "<head>"
                file.puts "	<meta charset=\"UTF-8\">"
                file.puts "	<meta content=\"IE=edge\" http-equiv=\"X-UA-Compatible\">"
                file.puts "	<meta content=\"initial-scale=1.0, maximum-scale=1.0, user-scalable=no, width=device-width\" name=\"viewport\">"
                file.puts "	<title>#{title}</title>"
                file.puts "	<link href=\"./css/base.min.css\" rel=\"stylesheet\">"
                file.puts "	<link href=\"./css/project.min.css\" rel=\"stylesheet\">"
                file.puts "</head>"
                file.puts "<body class=\"page-brand\">"
                file.puts "	<header class=\"header header-transparent header-waterfall ui-header\">"
                file.puts "		<ul class=\"nav nav-list pull-left\">"
                file.puts "			<li>"
                file.puts "				<a data-toggle=\"menu\" href=\"#ui_menu\">"
                file.puts "					<span class=\"icon icon-lg\">menu</span>"
                file.puts "				</a>"
                file.puts "			</li>"
                file.puts "		</ul>"
                file.puts "		<a class=\"header-logo header-affix-hide margin-left-no margin-right-no\" data-offset-top=\"213\" data-spy=\"affix\" href=\"index.html\">#{title}</a>"
                file.puts "		<span class=\"header-logo header-affix margin-left-no margin-right-no\" data-offset-top=\"213\" data-spy=\"affix\">Data Tables</span>"
                file.puts "	</header>"
                file.puts "	<nav aria-hidden=\"true\" class=\"menu\" id=\"ui_menu\" tabindex=\"-1\">"
                file.puts "		<div class=\"menu-scroll\">"
                file.puts "			<div class=\"menu-content\">"
                file.puts "				<a class=\"menu-logo\" href=\"index.html\">#{title} - Simon Bermudez</a>"
                file.puts "				<ul class=\"nav\">"
                file.puts "					<li>"
                file.puts "						<a class=\"waves-attach\" data-toggle=\"collapse\" href=\"#ui_menu_components\">Components</a>"
                file.puts "						<ul class=\"menu-collapse collapse in\" id=\"ui_menu_components\">"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-button.html\">Buttons</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-button-fab.html\">Buttons<small class=\"margin-left-xs\">(Floating Action Button)</small></a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-card.html\">Cards</a>"
                file.puts "							</li>"
                file.puts "							<li class=\"active\">"
                file.puts "								<a class=\"waves-attach\" href=\"ui-data-table.html\">Data Tables</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-dialog.html\">Dialogs</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-dropdown-menu.html\">Menus</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-nav-drawer.html\">Navigation Drawers</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-picker.html\">Pickers</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-progress.html\">Progress</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-selection-control.html\">Selection Controls</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-snackbar.html\">Snackbars</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-stepper.html\">Steppers</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-tab.html\">Tabs</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-text-field.html\">Text Fields</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-toolbar.html\">Toolbars</a>"
                file.puts "							</li>"
                file.puts "						</ul>"
                file.puts "					</li>"
                file.puts "					<li>"
                file.puts "						<a class=\"collapsed waves-attach\" data-toggle=\"collapse\" href=\"#ui_menu_extras\">Extras</a>"
                file.puts "						<ul class=\"menu-collapse collapse\" id=\"ui_menu_extras\">"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-avatar.html\">Avatars</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-icon.html\">Icons</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-label.html\">Labels</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-nav.html\">Navs</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-tile.html\">Tiles</a>"
                file.puts "							</li>"
                file.puts "						</ul>"
                file.puts "					</li>"
                file.puts "					<li>"
                file.puts "						<a class=\"collapsed waves-attach\" data-toggle=\"collapse\" href=\"#ui_menu_javascript\">Javascript</a>"
                file.puts "						<ul class=\"menu-collapse collapse\" id=\"ui_menu_javascript\">"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-affix.html\">Affix</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-collapse.html\">Collapse</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-dropdown-menu.html\">Dropdown</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-modal.html\">Modals</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"ui-tab.html\">Togglable Tabs</a>"
                file.puts "							</li>"
                file.puts "						</ul>"
                file.puts "					</li>"
                file.puts "					<li>"
                file.puts "						<a class=\"collapsed waves-attach\" data-toggle=\"collapse\" href=\"#ui_menu_samples\">Sample Pages</a>"
                file.puts "						<ul class=\"menu-collapse collapse\" id=\"ui_menu_samples\">"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"page-login.html\">Login Page</a>"
                file.puts "							</li>"
                file.puts "							<li>"
                file.puts "								<a class=\"waves-attach\" href=\"page-picker.html\">Picker Page</a>"
                file.puts "							</li>"
                file.puts "						</ul>"
                file.puts "					</li>"
                file.puts "				</ul>"
                file.puts "			</div>"
                file.puts "		</div>"
                file.puts "	</nav>"
                file.puts "	<main class=\"content\">"
                file.puts "		<div class=\"content-header ui-content-header\">"
                file.puts "			<div class=\"container\">"
                file.puts "				<div class=\"row\">"
                file.puts "					<div class=\"col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2\">"
                file.puts "						<h1 class=\"content-heading\">Resultados de la busqueda</h1>"
                file.puts "					</div>"
                file.puts "				</div>"
                file.puts "			</div>"
                file.puts "		</div>"
                file.puts "		<div class=\"container\">"
                file.puts "			<div class=\"row\">"
                file.puts "				<div class=\"col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2\">"
                file.puts "					<section class=\"content-inner margin-top-no\">"
                file.puts "						<div class=\"card\">"
                file.puts "							<div class=\"card-main\">"
                file.puts "							</div>"
                file.puts "						</div>"
                file.puts "						<h2 class=\"content-sub-heading\">Movie Info</h2>"
                file.puts "<div class=\"ui-card-wrap\">"
                file.puts "  <div class=\"row\">"

                movies.each { |movie|
                  extra = API.get("http://www.omdbapi.com/?t=#{movie["Title"]}&y=&plot=short&r=json")
                  file.puts "    <div class=\"col-lg-4 col-sm-6\">"
                  file.puts "      <div class=\"card\">"
                  file.puts "        <div class=\"card-main\">"
                  file.puts "          <div class=\"card-header\">"
                  file.puts "            <div class=\"card-header-side pull-left\">"
                  file.puts "              <div class=\"avatar\">"
                  file.puts "                <img alt=\"IMDB\" src=\"http://www.iconarchive.com/download/i75865/martz90/circle/imdb.ico\">"
                  file.puts "              </div>"
                  file.puts "            </div>"
                  file.puts "            <div class=\"card-inner\">"
                  file.puts "              <span class=\"card-heading\">#{movie["Title"]}</span>"
                  file.puts "            </div>"
                  file.puts "          </div>"
                  file.puts "          <div class=\"card-img\">"
                  file.puts "            <img alt=\"alt text\" src=\"#{movie["Poster"]}\" style=\"width: 100%;\">"
                  file.puts "            <p class=\"card-img-heading\">#{movie["Title"]}</p>"
                  file.puts "          </div>"
                  file.puts "          <div class=\"card-inner\">"
                  file.puts "            <p>"
                  file.puts "              <b>Fecha:</b> #{movie["Year"]}<br>"
                  file.puts "              <b>Decripcion:</b> #{extra["Plot"]}<br>"
                  file.puts "              <b>Genero:</b> #{extra["Genre"]}<br>"
                  file.puts "              <b>Actores:</b> #{extra["Actors"]}<br>"
                  file.puts "            </p>"
                  file.puts "          </div>"
                  file.puts "          <div class=\"card-action\">"
                  file.puts "            <div class=\"card-action-btn pull-left\">"
                  file.puts "              <a class=\"btn btn-flat waves-attach\" href=\"http://www.imdb.com/\"><span class=\"go\">check</span>&nbsp;Ir a IMDB</a>"
                  file.puts "            </div>"
                  file.puts "        </div>"
                  file.puts "      </div>"
                  file.puts "    </div>"
                  file.puts "  </div>"
              }
                file.puts "</div>"
                file.puts "								<div class=\"card-action\">"
                file.puts "									<div class=\"card-action-btn pull-right\">"
                file.puts "										<a class=\"btn btn-flat waves-attach\" href=\"javascript:void(0)\"><span class=\"icon\">chevron_left</span></a>"
                file.puts "										<a class=\"btn btn-flat waves-attach\" href=\"javascript:void(0)\"><span class=\"icon\">chevron_right</span></a>"
                file.puts "									</div>"
                file.puts "								</div>"
                file.puts "							</div>"
                file.puts "						</div>"
                file.puts "					</section>"
                file.puts "				</div>"
                file.puts "			</div>"
                file.puts "		</div>"
                file.puts "	</main>"
                file.puts "	<footer class=\"ui-footer\">"
                file.puts "		<div class=\"container\">"
                file.puts "			<p>#{title}</p>"
                file.puts "		</div>"
                file.puts "	</footer>"
                file.puts ""
                file.puts "	<!-- js -->"
                file.puts "	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js\"></script>"
                file.puts "	<script src=\"./js/base.min.js\"></script>"
                file.puts "	<script src=\"./js/project.min.js\"></script>"
                file.puts "</body>"
                file.puts "</html>"
            end
            Launchy.open(@fpath)
          #Launchy.open(ftp_upload)
          puts "Abriendo en el navegador...".yellow
          end
end
