SHOW DATABASES;

-- DDL
CREATE DATABASE DBNAME;
DROP DATABASE DBNAME;
CREATE TABLE;
ALTER TABLE;
DROP TABLE;
TRUNCATE TABLE NAME;

-- DML
INSERT INTO NAME (CAMPOS) VALUES (VALORES);
UPDATE NAME;

UPDATE (NAME);
SET FIELD = VALUES;
WHERE CONDITION;